//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucHanhLanCuoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ProductID { get; set; }
        public int CategoryID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public decimal ProductPrice { get; set; }
        public string ProductImage { get; set; }
        public DateTime DateAdded { get; set; } = DateTime.Now;
        public decimal? SalePrice { get; set; } // Giá sau giảm giá
        public bool IsSale => SalePrice.HasValue && SalePrice < ProductPrice; // Kiểm tra có giảm giá hay không
        public decimal SalePercentage
        {
            get
            {
                if (IsSale && SalePrice.HasValue)
                {
                    return Math.Round(100 * (ProductPrice - SalePrice.Value) / ProductPrice, 2);
                }
                return 0;
            }
        }
        public string FormattedProductPrice
        {
            get
            {
                return String.Format("{0:N0}vnd", ProductPrice); // Định dạng giá với dấu phân cách hàng nghìn
            }
        }
        public bool IsNew => (DateTime.Now - DateAdded).TotalDays <= 30; // Kiểm tra hàng mới (trong 30 ngày)

        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
